name: igdb_client
description: A dart library for IGDB API
version: 0.0.1
homepage: https://github.com/mitchhymel/dart-igdb_client
author: mitchhymel

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http:

dev_dependencies:

