name: igdb_client
description: A dart library for IGDB API
version: 0.0.7
homepage: https://github.com/mitchhymel/dart-igdb_client

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  fixnum: ^1.1.0
  http: ^1.1.0
  protobuf: ^3.0.0
  protoc_plugin: ^21.0.2

dev_dependencies:
  lint: ^2.1.2
