name: igdb_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Mitchell <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http:

dev_dependencies:

